@extends('layouts.main')

@section('content')
<div class='about'>
  <h2>What is this?</h2>
  <p><a href="{{$_ENV['APP_URL']}}">{{$_ENV['APP_URL']}}</a> is a site that allows you to generate your own <a href='https://www.antisocialsocialclub.com/'>Anti Social Socal Club</a> logo that looks like
    the classic T-Shirt logo we all know and loved. You can find Custom <a href='https://thomashobohm.com/supreme/'>Supreme Logo Generators</a> all over the internet but when it comes to more complicated logos like
    Anti Social Social Club you cant find anything.
    <br><br>
    Typically, if you wanted your own logo you would have to hire your own designer or hit up <a href='https://www.fiverr.com/samueltakesoff/make-a-custom-anti-social-club-logo-streetwear-hypebeast'>Fivver</a>. With this service you can type in some text on <a href='/'>the main page</a>
    and generate your own custom Anti Anti Social Club Logo.
    <br><br>
    The logo is <b>FREE</b>! While you're here you may want to checkout what has <a href='/gallery'>already been generated by the community</a>. After you generate your custom Anti Social Social Club logo
    you can then even get your own mech with your logo on it!
    <br><br>
    This generator does take some money to run as the process to do this actually isnt as simple as you think. If you like the ASSC logos we have generated or
    the ASSC custom logo we generated for you feel free to donate to the developer:
    <br>
    VENMO: <a href='https://github.com/timothycarambat'>@tim-carambat</a>
    <br><br>
    The merchandise is made on demand so there is no mimiumum! All merchandise is <b>FREE WORLDWIDE SHIPPING</b>.
    <br><br>
    Go ahead and get started now!
  </p>
</div>
@endsection
