@extends('layouts.main')

@section('content')
<div class='privacy'>
<h2>Industrial Object Terms of Service</h2>
<h3>1. Terms</h3>
<p>By accessing the website at <a href="https://antisomethingsomethingclub.com">https://antisomethingsomethingclub.com</a>,
  you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for
  compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
  The materials contained in this website are protected by applicable parody law.</p>
<h3>2. Use License</h3>

<ol type="a">
   <li>Permission is granted to download one copy of the materials (information or software) on Industrial Object's website for any use.
     This website and content generated by users within are not reflective of the views of INDUSTRIAL OBJECT or any person(s) relating to the business.
     This content generated by users on this site is reviewed often for removal due to the following, but not limited to, reasons:
   <ol type="i">
       <li>Racist or derogatory content</li>
       <li>Use of protected language or trademarks</li>
       <li>Illicit phrases or content</li>
       <li>Owner Discretion</li>
   </ol>
    </li>
   <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by Industrial Object at any time.</li>
</ol>
<h3>3. Disclaimer</h3>
<ol type="a">
   <li>The materials on Industrial Object's website are provided on an 'as is' basis. Industrial Object makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</li>
   <li>Further, Industrial Object does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</li>
</ol>
<h3>4. Limitations</h3>
<p>In no event shall Industrial Object or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Industrial Object's website, even if Industrial Object or a Industrial Object authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
<h3>5. Accuracy of materials</h3>
<p>The materials appearing on Industrial Object's website could include technical, typographical, or photographic errors. Industrial Object does not warrant that any of the materials on its website are accurate, complete or current. Industrial Object may make changes to the materials contained on its website at any time without notice. However Industrial Object does not make any commitment to update the materials.</p>
<h3>6. Links</h3>
<p>Industrial Object has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Industrial Object of the site. Use of any such linked website is at the user's own risk.</p>
<h3>7. Modifications</h3>
<p>Industrial Object may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>
<h3>8. Governing Law</h3>
<p>These terms and conditions are governed by and construed in accordance with the laws of California and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
<h3>9. Your Data</h3>
<p>You own any and all data releated to the order fulfillment. You may request to view or delete data at any time by contacting our <a href="mailto:{{$_ENV['SUPPORT_EMAIL']}}">SUPPORT EMAIL</a>.
  <br>
  Under no circumstance is your information sold, resused, or leveraged in any capcaity to third parties or matters unreleated to this website or service.
</p>
</div>
@endsection
